
DAILY='DAILY'
WEEKLY='WEEKLY'
MONTHLY='MONTHLY'
ANNUALLY='ANNUALLY'

MONTHLY_MEAN='MONTHLY_MEAN'
ANNUAL_MEAN='ANNUAL_MEAN'
MONTHLY_SUM='MONTHLY_SUM'
ANNUAL_SUM='ANNUAL_SUM'
MONTHLY_SNAPSHOT='MONTHLY_SNAPSHOT'
ANNUAL_SNAPSHOT='ANNUAL_SNAPSHOT'